name: Alpha-Folder Otonom Dongu

on:
  schedule:
    - cron: '0 0 * * *' # Her gece 00:00'da otomatik calis
  workflow_dispatch: # Manuel baslatma butonu ekler

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Bagimliliklari Yukle
        run: |
          pip install requests fpdf google-generativeai

      - name: Makineyi Calistir
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py
